medical appointments plugin functionality
anddy665/appointment-harrison pull request #4
Opened 2024-11-07 16:38 UTC by Harrisong-Gutierrez

2024-11-07 22:46 UTC, anddy665 requested changes

2024-11-07 22:46 UTC, anddy665 commented on admin/assets/js/index.js
> +
Elimina estos saltos de lineas que estan de mas

2024-11-07 22:46 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +class AppointmentsHandler
Que todas las clases esten en Singular y no en plurar

2024-11-07 22:46 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +            wp_redirect(admin_url('admin.php?page=appointments'));
La URL esta Quemada

2024-11-07 22:46 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +            wp_redirect(admin_url('admin.php?page=appointments'));
Igual falta Validacion en caso que falle el Delete

2024-11-07 22:46 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +                "{$wpdb->prefix}appointments",
Deja esto en una variable mas arriba es para evitar en cada consulta este poniendo lo mismo si lo puedes dejar en un archivo de variables globales mejor porque seguro utilizaras el nombre de la base de datos en muchos lugares 

` "{$wpdb->prefix}appointments",`

2024-11-07 22:46 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +        global $wpdb;
declara $wpdb de manera global en la clase para q no tengas que hacer la misma declaracion en cada funcion

2024-11-07 22:46 UTC, anddy665 commented on admin/templates/appointments-page.php
> +require_once plugin_dir_path(__FILE__) . '../inc/AppointmentsHandler.php';
esto ya lo tenias en variables globales no se porque no las estas usando
`plugin_dir_path(__FILE__)`

2024-11-07 22:46 UTC, anddy665 commented on appointments.php
>  class AppointmentsPlugin
clase en singular podes dejarlo solo como Appointment

2024-11-07 22:46 UTC, anddy665 commented on appointments.php
> +            echo '<p>Cita agendada correctamente</p>';
Utiliza un template para los mensajes

2024-11-07 22:46 UTC, anddy665 commented on appointments/inc/AppointmentFormWidget.php
> +        global $wpdb;
declaralo solo una vez en las clases para que no lo tengas que declaras en cada funcion como en los archivos anteriores

2024-11-07 22:46 UTC, anddy665 commented on appointments/inc/AppointmentFormWidget.php
> +class AppointmentFormWidget extends WP_Widget
quita todo lo referente a widget y imprime el from con shortcode

2024-11-07 22:46 UTC, anddy665 commented on appointments.php
> +            $full_name = sanitize_text_field($_POST['full_name']);
Single Responsibility Principle (SRP)

2024-11-08 15:25 UTC, Harrisong-Gutierrez commented on admin/assets/js/index.js
> +
done

2024-11-13 15:00 UTC, anddy665 requested changes

2024-11-13 15:00 UTC, anddy665 commented on appointments/inc/AppointmentsClass.php
> +interface AppointmentDatabaseInterface
Crea una ruta para las interfaces ejemplo:

appointments/
├── inc/
│   ├── interfaces/
│   │   ├── YourInterface1.php
│   │   └── YourInterface2.php
└── templates/

2024-11-13 15:00 UTC, anddy665 commented on appointments/inc/AppointmentsClass.php
> +    public function insertAppointment($full_name, $email, $phone, $appointment_date, $start_time, $end_time, $description)
esta funcion no deberia de ir aqui

2024-11-13 15:00 UTC, anddy665 commented on appointments/inc/AppointmentsClass.php
> +        $table = $wpdb->prefix . 'appointments';
si ya creaste la Variable Global porque no la usas y vuelves a definir una variable

2024-11-13 15:00 UTC, anddy665 commented on appointments/inc/AppointmentFormShortcode.php
> +    public function insertAppointment($full_name, $email, $phone, $appointment_date, $start_time, $end_time, $description)
Vuelves a tener la funcion Duplicada.

2024-11-13 21:44 UTC, anddy665 requested changes

2024-11-13 21:44 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +
no dejes tanto espacio tantos enters

2024-11-13 21:44 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +            wp_redirect(admin_url('admin.php?page=appointments'));
usa las variables globales

2024-11-13 21:44 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +            wp_redirect(admin_url('admin.php?page=appointments'));
La URL Esta quemada usa variable globales

2024-11-13 21:44 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +        if ($appointments === false) {
esta validacion esta mala validas que si no hay nada en appointment imprima un mensaje en los error logs pero luego el codigo sigue entonces en el return devuelve un false valida bien eso.

2024-11-13 21:44 UTC, anddy665 commented on admin/inc/AppointmentsHandler.php
> +        if ($appointment === null) {
igual esta validacion esta incompleta

2024-11-13 21:44 UTC, anddy665 commented on admin/inc/BaseController.php
> +        $results = $this->wpdb->get_results("SELECT * FROM {$this->wpdb->prefix}schedules");
no estas usando la variable global para referirte a la tabla Schedule

2024-11-13 21:44 UTC, anddy665 commented on admin/inc/SchedulesController.php
>      {
porque tienes todo este codigo en el constructor dejalo afuera en funciones

2024-11-13 21:44 UTC, anddy665 commented on appointments.php
>      public function addAdminMenu()
Y esta funcion para que sirve??

2024-11-15 17:36 UTC, anddy665 requested changes

2024-11-15 17:36 UTC, anddy665 commented on appointments/inc/AppointmentFormShortcode.php
> +        include plugin_dir_path(__FILE__) . '../templates/appointment-form-template.php';
Recorda utilizar la funcion loadTemplate que creaste y no uses include

2024-11-15 17:36 UTC, anddy665 commented on appointments/inc/AppointmentFormShortcode.php
> +            "SELECT id FROM {$this->wpdb->prefix}schedules WHERE schedule_date = %d",
Usa las variables Globales para el nombre de la tabla

2024-11-15 17:36 UTC, anddy665 commented on appointments.php
> +    public function handleAppointmentFormSubmission()
Revisa esta funcion parece duplicada con lo que esta en appointmentsformshortcode.php

2024-11-15 17:36 UTC, anddy665 commented on appointments/templates/appointment-form-template.php
> +<style>
sacar estilos y javascript de esta vista

2024-11-15 17:36 UTC, anddy665 commented on admin/templates/appointments-page.php
> +$appointmentHandler->handleFormSubmission();
if $appointmentHandler == error{
echo 'imprimi el error'
}else {
wp_redirect home/
}

2024-11-22 15:30 UTC, anddy665 requested changes

2024-11-22 15:30 UTC, anddy665 commented on appointments/inc/AppointmentsClass.php
> -        CREATE TABLE $table_appointments (
Usa las variables globales para los nombres de las tablas revisa el archivo completo.

2024-11-22 16:09 UTC, anddy665 approved these changes

2024-11-22 16:09 UTC, merged